
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 19 16:26:36 CET 2025
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 4;
  public static final int MAP = 22;
  public static final int LBRACKET = 46;
  public static final int INCREMENT = 38;
  public static final int CONST = 10;
  public static final int LESSE = 34;
  public static final int LPAREN = 44;
  public static final int SEMI = 40;
  public static final int GREATER = 31;
  public static final int CONTINUE = 18;
  public static final int INTERFACE = 23;
  public static final int NUM_CONST = 3;
  public static final int DECREMENT = 39;
  public static final int LESS = 33;
  public static final int MINUS = 25;
  public static final int RPAREN = 45;
  public static final int IS = 37;
  public static final int AND = 35;
  public static final int OR = 36;
  public static final int COMMA = 42;
  public static final int CLASS = 8;
  public static final int DIV = 27;
  public static final int PLUS = 24;
  public static final int IF = 11;
  public static final int DOT = 43;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int RBRACKET = 47;
  public static final int EQUAL = 29;
  public static final int NEW = 12;
  public static final int error = 1;
  public static final int MUL = 26;
  public static final int GREATERE = 32;
  public static final int MOD = 28;
  public static final int BREAK = 7;
  public static final int IDENT = 2;
  public static final int VOID = 16;
  public static final int COLON = 41;
  public static final int UNION = 19;
  public static final int LBRACE = 48;
  public static final int ELSE = 9;
  public static final int READ = 14;
  public static final int WHILE = 21;
  public static final int NEQUAL = 30;
  public static final int RBRACE = 49;
  public static final int EXTENDS = 17;
  public static final int PROG = 6;
  public static final int BOOL_CONST = 5;
  public static final int PRINT = 13;
  public static final int DO = 20;
}

